name: webengine # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  webengine:
    command: desktop-launch simplebrowser
    plugs:
        - avahi-observe
        - browser-support
        - camera
        - cups-control
        - desktop
        - desktop-legacy
        - gsettings
        - home
        - network
        - network-observe
        - opengl
        - pulseaudio
        - removable-media
        - screen-inhibit-control
        - u2f-devices
        - unity7
        - upower-observe
        - x11
        - hostname-control
        - mount-observe

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

parts:
  appdir:
    plugin: dump
    source: appdir/
    after:
      - desktop-gtk3
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
